server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://db-animore.cq7hhy9uh3a2.ap-northeast-2.rds.amazonaws.com:3306/animore?
    username: root
    password: Animore100!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f8dc53cf8c5452b17f33260931bb4014
            client-secret: FCHKqialO9oxtStnOliZsVrubEolwDmM
            scope: profile_nickname,account_email,gender
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST

          naver:
            client-id: HZl59ItB9qgvLI7S49iu
            client-secret: v6SemnBc8V
            scope: id, nickname, name, email, gender
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-authentication-method: POST

          facebook:
            client-id: 1221566275198331
            client-secret: 3a993ac29f1b49d46608417f16a52a13
            scope: public_profile, email


          google:
            client-id: 868335399925-2n7t9a1kgckmom5ai4b0rrhofm7a32e0.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


upload:
  path: \src\main\resources\templates\image\

